AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
